language: python
cache: pip

python:
  - "3.4"
  - "3.5"

install:
  - npm install -g apidoc
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest-flask

before_script:
  - python manage.py syncdb
  - make apidoc

script:
  - py.test
