web:
  restart: always
  build: .
  volumes:
    - .:/code/
  expose:
      - "5000"
  command: gunicorn -w 4 -b :8000 api_service:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
